# Generated by Django 4.1.7 on 2023-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logoslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
