# Generated by Django 4.1.7 on 2023-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0002_logoslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoslider',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logoslider',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
