# Generated by Django 4.1.7 on 2023-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0003_logoslider_height_logoslider_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
