# Generated by Django 4.1.7 on 2023-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0004_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.TextField(max_length=100)),
                ('rank', models.TextField()),
            ],
        ),
    ]
