# Generated by Django 4.1.7 on 2023-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0006_category_projectdetail_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='projectName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='enddate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='startdate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
