# Generated by Django 4.1.7 on 2023-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0007_alter_portfolio_projectname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
