# Generated by Django 4.1.7 on 2023-06-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0008_locationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
