# Generated by Django 4.1.7 on 2023-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0009_alter_locationdetail_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_category', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
