# Generated by Django 4.2.3 on 2023-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0011_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='head0',
            field=models.CharField(default='', max_length=107),
        ),
    ]
