# Generated by Django 4.2.3 on 2023-09-11 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0014_rename_category_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head3',
        ),
        migrations.AlterField(
            model_name='blog',
            name='head1',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='startdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='Desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
