# Generated by Django 4.2.3 on 2023-09-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0017_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='contactform',
            name='pcategory',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
