# Generated by Django 4.2.3 on 2023-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0019_alter_contactform_pcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_category',
            name='plan',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
