# Generated by Django 4.2.3 on 2023-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0020_alter_pricing_category_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='pcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
