# Generated by Django 4.2.3 on 2023-09-26 09:03

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0021_alter_contactform_pcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='head1',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing_category',
            name='plan',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
