# Generated by Django 4.2.3 on 2023-09-26 12:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0023_alter_contactform_message_alter_projectdetail_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
