# Generated by Django 4.2.3 on 2023-09-26 13:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0024_alter_policy_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_condition', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
