# Generated by Django 4.2.3 on 2023-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0027_alter_socialmediaprofile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'linkedin'), ('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('pinterest', 'pinterest'), ('youtube', 'youtube')], max_length=20),
        ),
    ]
