# Generated by Django 4.2.3 on 2023-10-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0028_alter_socialmediaprofile_platform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='icon',
        ),
    ]
