# Generated by Django 4.2.3 on 2023-10-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0029_delete_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_icon', models.ImageField(upload_to='pics/icon')),
                ('logo', models.ImageField(upload_to='pics/icon')),
            ],
        ),
    ]
