# Generated by Django 4.2.3 on 2023-10-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0030_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='icon',
        ),
    ]
