# Generated by Django 4.2.3 on 2023-11-02 06:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0031_delete_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', ckeditor.fields.RichTextField()),
                ('ans', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
