# Generated by Django 4.2.3 on 2023-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0033_alter_faq_ans_alter_faq_quest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='award',
        ),
        migrations.RemoveField(
            model_name='logoslider',
            name='height',
        ),
        migrations.RemoveField(
            model_name='logoslider',
            name='width',
        ),
        migrations.AddField(
            model_name='logoslider',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
