# Generated by Django 4.2.3 on 2023-11-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0035_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='title',
            new_name='title_logo',
        ),
    ]
