# Generated by Django 4.2.3 on 2023-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0036_rename_title_logo_title_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='pics/icons'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='title_logo',
            field=models.ImageField(upload_to='pics/icons'),
        ),
    ]
