# Generated by Django 4.2.3 on 2023-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0037_alter_logo_logo_alter_logo_title_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='head0',
        ),
    ]
