# Generated by Django 4.2.3 on 2024-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0039_alter_blog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pricing_category',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='pcategory',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
    ]
