# Generated by Django 5.0.4 on 2024-05-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitor', '0040_delete_pricing_category_remove_contactform_pcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='help_category',
        ),
    ]
